version: '3.8'

services:
  data-processor:
    image: data-processor
    volumes:
      - ./Data/Input:/Data/Input
      - ./Data/Output:/Data/Output
    environment:
      - InputFilePath=/Data/Input/OutputOfTask_A.txt
      - OutputFilePath=/Data/Output/OutputOfTask_C.txt